spark:
  driver:
    allowMultipleContexts: true
mongodb:
  url: mongodb:27017
  name: lime
  collections:
    users: users
    transactions: transactions
elasticsearch:
  host: elastic
  port: 9300
  clustername: elasticsearch
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration