mongodb:
  url: mongodb:27017
  name: lime
  collections:
    users: users
    transactions: transactions
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration