version: '2'
services:
  postgresql:
    container_name: postgresql
    image: library/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=processing

  processing:
    container_name: processing
    build:
      context: .
      dockerfile: Dockerfile
    image: lime/processing
    ports:
      - "8080:8080"
    links:
      - postgresql
