version: '2'
services:
  mongodb:
    container_name: mongodb
    image: library/mongo
    ports:
      - "27017:27017"

  transaction-generator:
    container_name: transaction-generator
    build:
      context: .
      dockerfile: Dockerfile
    image: lime/transaction-generator
    environment:
      JAVA_OPTS: '-Dsize=2000 -DdropExisting=true'
    links:
      - mongodb
