version: '2'

services:
  mongodb:
    container_name: mongodb
    image: library/mongo
    ports:
      - "27017:27017"

  elastic:
    container_name: elastic
    image: elasticsearch:2.4
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - cluster.name=default
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  transaction-generator:
    container_name: transaction-generator
    image: elizabbeth/transaction-generator
    environment:
      JAVA_OPTS: '-Dsize=2000 -DdropExisting=true'
    links:
      - mongodb

  user-profile-service:
    container_name: user-profile-service
    image: elizabbeth/user-profile-service:latest
    ports:
      - "8082:8080"
    links:
      - mongodb
      - elastic