CREATE TABLE UserBalance (
  UserID INTEGER NOT NULL,
  Balance DECIMAL NOT NULL DEFAULT 0,
  PRIMARY KEY (UserID)
);

CREATE TABLE Transactions (
  TransactionID VARCHAR(255) NOT NULL,
  UserID INTEGER DEFAULT NULL,
  BusinessID INTEGER NOT NULL,
  Type SMALLINT DEFAULT 0,
  Status SMALLINT,
  PaymentAmount DECIMAL,
  Payback DECIMAL DEFAULT NULL,
  PRIMARY KEY (TransactionID),
  FOREIGN KEY (UserID) REFERENCES UserBalance(UserID)
);
