spring:
  jackson:
    serialization:
      fail_on_empty_beans: false
  datasource:
    url: jdbc:postgresql://postgresql:5432/processing
    username: postgres
    password: root
flyway:
  baseline-on-migrate: true
logging:
  level:
    org.postgresql: debug